name: filmflix

description: "Yet Another Movies App."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.6.2
  equatable: ^2.0.7
  dartz: ^0.10.1
  dio: ^5.7.0
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.3.1
  readmore: ^3.0.0
  stream_transform: ^2.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/